### ISSUE TITLE
DRC run stuck for more than 10 hours in 1 rule

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#17] opened 2022-12-06 09:30 UTC
## Expected Behavior
Finish the DRC run in a reasonable time

## Actual Behavior
When running both deep mode and flat mode, DRC run gets stuck in `2022-12-05 15:47:30 -0800: Memory Usage (8372300K) : Executing rule CO.6a` for more than 10 hours now.

This is running on full caravel chip: [source gds](https://github.com/efabless/caravel-gf180mcu/blob/PnR/gds/caravel.gds.gz)

## Steps to Reproduce the Problem

1. `python3 run_drc.py --thr=4 --variant=C --path=/home/marwan/caravel-gf180mcu/gds/caravel.gds --run_dir=/home/marwan/caravel-gf180mcu/signoff/caravel/standalone_pvr`

## Specifications

- Version: `KLayout 0.28` commit `b3968c31e5b06325e071b4a79ff9f35979e07bda`
- Platform: `Debian`

**Comment by marwaneltoukhy** [comment] 2022-12-06 10:42
It also got stuck in `CO.6` for 5 hours
```
2022-12-05 10:17:34 -0800: Memory Usage (8379444K) : Executing rule CO.6
2022-12-05 15:47:30 -0800: Memory Usage (8372300K) : Executing rule CO.6a
```

**Comment by klayoutmatthias** [comment] 2022-12-08 22:22
I can't do much against flat mode performance.

But I see that in the latest main branch, the input layers are merged after reading them. This has a bad effect in deep mode, specifically for metal1 which participates in the contact checks. 

I proposed not to merge them, but I guess that patch got lost during the refactoring (which I basically think is a good idea).

I'll try to patch it back and run the test in deep mode. Let's see what the run times are then.

Matthias

**Comment by klayoutmatthias** [comment] 2022-12-08 23:14
One first data point after this patch:

`DF.2b_3.3V` and `DF.2b_5V` take very long (about 1hr CPU time). It's probably due to the long-range width check. It runs fast but I think it delivers very complex output polygons.

A super fast and IMHO more correct implementation is this:

```
df_2b = comp.not_inside(mos_cap_mk).sized(-50.um).sized(50.um)
# Rule DF.2b_3.3V: Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.
logger.info("Executing rule DF.2b_3.3V")
df2b_l1 = df_2b.not_interacting(v5_xtor).not_interacting(dualgate)
df2b_l1.output("DF.2b_3.3V", "DF.2b_3.3V : Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.")
df2b_l1.forget

# Rule DF.2b_5V: Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.
logger.info("Executing rule DF.2b_5V")
df2b_l1 = df_2b.overlapping(dualgate)
df2b_l1.output("DF.2b_5V", "DF.2b_5V : Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.")
df2b_l1.forget

df_2b.forget
```

The "size" will leave all areas which dimensions >100 µm. Oversize restores the original shape (or the parts bigger than 100µm).

The original solution is that:

```
df_2b = comp.width(100.um + 1.dbu).polygons(0.001).not_inside(mos_cap_mk)
# Rule DF.2b_3.3V: Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.
logger.info("Executing rule DF.2b_3.3V")
df2b_l1 = comp.not_inside(mos_cap_mk).not_interacting(df_2b).not_interacting(v5_xtor).not_interacting(dualgate)
df2b_l1.output("DF.2b_3.3V", "DF.2b_3.3V : Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.")
df2b_l1.forget

# Rule DF.2b_5V: Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.
logger.info("Executing rule DF.2b_5V")
df2b_l1 = comp.not_inside(mos_cap_mk).not_interacting(df_2b).overlapping(dualgate)
df2b_l1.output("DF.2b_5V", "DF.2b_5V : Max. COMP width for all cases except those used for capacitors, marked by ‘MOS_CAP_MK’ layer.")
df2b_l1.forget

df_2b.forget
```

I think the original solution is not correct as "not_interacting" would skip a big-area comp which is has a small appendix that locally interacts with df_2b.

Matthias

**Comment by klayoutmatthias** [comment] 2022-12-08 23:25
omg ... there is so much optimization potential ...

DF12:

```
# instead of: ..not_interacting(nplus.or(pplus)) + avoid duplication computation:
df12_l2 = comp.not_interacting(schottky_diode)
df12_l3 = comp.interacting(comp.not(nplus).not(pplus))
# Rule DF.12_3.3V: COMP not covered by Nplus or Pplus is forbidden (except those COMP under marking).
logger.info("Executing rule DF.12_3.3V")
df12_l1 = df12_l3.not_interacting(v5_xtor).not_interacting(dualgate)
df12_l1.output("DF.12_3.3V", "DF.12_3.3V : COMP not covered by Nplus or Pplus is forbidden (except those COMP under marking).")
df12_l1.forget

# Rule DF.12_5V: COMP not covered by Nplus or Pplus is forbidden (except those COMP under marking).
logger.info("Executing rule DF.12_5V")
df12_l1 = df12_l3.overlapping(dualgate)
df12_l1.output("DF.12_5V", "DF.12_5V : COMP not covered by Nplus or Pplus is forbidden (except those COMP under marking).")
df12_l1.forget

df12_l2.forget
df12_l3.forget
```

**Comment by klayoutmatthias** [comment] 2022-12-09 00:08
A basic difference between this test case and the other cases is the cap mesh around the chip. 

For this mesh, DRC commands like `pplus.or(nplus)` generate huge polygons ("or" merges shapes!) which spoils the performance in some parts.

e.g. SB.15:

```
poly2.interacting(nplus.or(pplus))   # -> 1468s
poly2.interacting(nplus + pplus)     # -> 16s ("+" does not merge)
```

**Comment by klayoutmatthias** [comment] 2022-12-09 00:19
But after disabling the merge, CO.6a appears to be executing in <30s, CO.6 even less.

So bottom line is: 
* the DRC should disable the input layer merge in deep mode again. This will speed up CO and backend checks.
* There are some other low hanging fruits to optimize the DRC in the frontend area
* I believe a total run time of <1hr for this test case is possible (connectivity checks disabled)

Matthias

**Comment by atorkmabrains** [comment] 2022-12-09 05:48
@klayoutmatthias 

I have a concern about not merging related to some checks where the polygons are touching each other and we depend on counts for example. Klayout counts them as 2 while if you look at the layout they are only 1 merged polygon. Merging for me is a must to make sure of proper DRC functionality

**Comment by klayoutmatthias** [comment] 2022-12-10 00:45
@atorkmabrains No, KLayout will implicitly merge where required. This is meant by "merged semantics".

Here is a code example for the deep mode "interact", "inside", "outside" or "covering" operation (`dbDeepRegion.cc:2002++`):

```
  bool counting = !(min_count == 1 && max_count == std::numeric_limits<size_t>::max ());

  std::unique_ptr<db::DeepRegion> dr_holder;
  const db::DeepRegion *other_deep = dynamic_cast<const db::DeepRegion *> (other.delegate ());
  if (! other_deep) {
    //  if the other region isn't deep, turn into a top-level only deep region to facilitate re-hierarchization
    dr_holder.reset (new db::DeepRegion (other, const_cast<db::DeepShapeStore &> (*deep_layer ().store ())));
    other_deep = dr_holder.get ();
  }

  const db::DeepLayer &polygons = merged_deep_layer ();
  //  NOTE: with counting, the other polygons must be merged
  const db::DeepLayer &other_polygons = counting ? other_deep->merged_deep_layer () : other_deep->deep_layer ();
```

So the primary layer is implicitly merged ("merged_deep_layer"). This is required as "interact" or "inside" is supposed to deliver the full, merged polygon. But the second input ("other") is only merged when counts are involved. If not, the processor will look up all shapes that interact with the primary, merged shape. This information is sufficient to determine whether the primary is to be selected. No merging of the secondary input is required.

For example, when testing `contact.inside(comp)`, this boosts performance as `comp` is a distributed layer potentially forming huge meshes on merge. But usually it's made of many small pieces that stitch together. Contact on the other hand is local. Merging contacts is cheap and the processor will only need the local `comp` parts to determine whether a contact is inside `comp` or not. Merging comp means each contact needs to be checked vs. a potentially huge `comp` polygon. 

BTW: `or` in KLayout is not what Calibre does. The KLayout equivalent of `or` is `join` or `+`. `or` will merge the involved layers and potentially produce large polygons. So this statement has very bad performance for the reasons explained above:

```
contact.inside(comp.or(poly2))
```

while this one (with 0.28) is much faster:

```
contact.inside(comp + poly2)
```

So not merging is the key to deep mode performance. Deep mode tries to avoid merging where possible. To give another example, DRC checks usually do not need to merge as the local vicinity of a shape is sufficient to detect width or space violations. However, you may observe multiple markers - one for each component of a shape cluster. If you worry about what happens when you work with edges derived from such markers: edges are also subject to implicit merging, so that should not be an issue.

Tiled mode is an exception, because the tiles may cut away pieces you're interested in. Choosing a reasonable border width that captures all "interesting" features may be an option, but that may not always be possible. In tiled and flat mode, merging is maybe acceptable, although at least in flat mode it should not be required as implicit merging applies there as well.

In deep mode you should be able to skip the merge step. If you observe anything else, that is a bug.

Merging in general spoils the hierarchy and in the test case this ticket applies to, merging will generate giant polygons for the cap meshes and power wiring. Merging is prohibitive in that case.

Matthias

**Comment by klayoutmatthias** [comment] 2022-12-10 17:37
There is another one:

```
metal3.enclosing(via3, ...)
```

takes forever (deep mode), while 

```
via3.enclosed(metal3, ...)
```

is fast. 

The reason is that the first input layer is implicitly merged (see https://github.com/KLayout/klayout/issues/1217). If via3 is the first layer, this does not do any harm. If metal3 is the first layer, this will render giant polygons and a long run time.

Matthias

**Comment by klayoutmatthias** [comment] 2022-12-11 12:48
Last comment from my side: I have proposed a patch to fix this issue (https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/19).

With this branch, the full DRC deck executes in 2700s (4 threads, deep mode, no connectivity checks, klayout 0.28 from yesterday's release, i7 at 2.7GHz). I think that is a reasonable time given the complexity of the layout and there is still some optimization potential if you are not satisfied yet.

Some DRC violations are flagged in the output and all IMHO are valid. Some are false positives:
* Some poly resistors are getting flagged as NW.1b_3.3V width violation if they are placed inside NW. I think this is an implementation issue
* Apparently the layout is made for 6LM which I can't enable (option D?). So V4.4a fails as metal5 is drawn on layer 81 (metal5) rather than 53 (metal_top).

The PR #19 proposes some changes which have not been accepted the first time I came up with them. So basically it's up to you to decide whether you want to have them or not. I personally think, they are good, but I cannot really assess the results of the regression tests as there are too many inherent fails. In any case, without these patches (specifically skipping the initial merge and reimplementation of LDMOS rules), IMHO there is no way to get reasonable performance. 

Matthias

**Comment by atorkmabrains** [comment] 2022-12-11 20:03
@klayoutmatthias I took many of the changes in #19 with the exception of merge as I was worried of how it works. As you confirmed it works correctly. I took everything here into the development area: https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr

**Comment by atorkmabrains** [comment] 2022-12-11 20:05
@klayoutmatthias I could confirm massive runtime gains with deep mode here:
via1 DRC Total Run time 135.274124 seconds

**Comment by atorkmabrains** [comment] 2022-12-11 22:22
I'll close this as this is fixed now.

**Closed as completed by atorkmabrains** 2022-12-11 22:22 UTC

**Comment by klayoutmatthias** [comment] 2022-12-12 21:50
Thanks :)

I took a look at your development fork and it's main head and to me it looks like the contact section is wip (e.g. `CO.6b` wasn't working correctly and the proper way to use "square_limits" in size is without quotes :) ). So I stopped for now, but I think there are some patches you still like to apply. Like the "enclosing" change from `metal.enclosing(via...` to `via.enclosed(metal, ...` which also applies to contact/poly/metal1 in a few places.

I also did not see some of the `comp` section changes I proposed, but I'll stop bugging you for now as I assume you have plenty other things to do :)

Anyway, I think there are many optimization opportunities. We'll sort them out finally.

Best regards,

Matthias

**Comment by atorkmabrains** [comment] 2022-12-13 15:45
@klayoutmatthias No please bug me. I appreciate that. Could you create a new PR on mabrains repo with the comp changes? Appreciate if you could do that. Or just create an issue there with the comp changes proposal.

**Comment by klayoutmatthias** [comment] 2022-12-14 20:36
I will do so. 

But maybe can you take a look? It looks like I cannot file issues on your fork. I don't see an "issues" tab :(

Matthias

**Comment by atorkmabrains** [comment] 2022-12-14 21:08
@klayoutmatthias I'll enable issues on my fork.
